### ISSUE TITLE
Children of Async::Container::Forked refuse to die

### ISSUE THREAD

**Issue by ainar-g** [socketry/async-container#1]
Not sure if this is an `async-container` bug or a `falcon` bug. Some init systems use SIGTERM to terminate a process. Falcon's main process does terminate, but children remain binded to the port, so the new instance fails with EADDRINUSE. The following monkey-patch of `Async::Container::Forked#wait` solves the issue:

```rb
module Async
  module Container
    class Forked
      def wait
        Signal.trap("TERM") do
          STDERR.puts("[ABRAHAM ] TERM received; killing all children")

          @pids.each do |pid|
            begin
              ::Process.kill(:TERM, pid)
            rescue StandardError => e
              STDERR.puts("[ABRAHAM ] can't kill child process #{ pid }: #{ e.message }")
            end
          end

          STDERR.puts("[ABRAHAM ] done")
        end

        return if @finished

        @pids.each do |pid|
          ::Process.wait(pid)
        end

        @finished = true
      end
    end
  end
end
```

**Comment by ioquatix** [comment]
Does it send SIGTERM to the top process or to the process group?

What's the logical behaviour?

**Comment by ainar-g** [comment]
Yes, the init system sends SIGTERM to the master process, which dies, but the child processes keep hanging on the port.

I think the logical behaviour would be to trap SIGTERM and call `Async::Container::Forked#stop`.

**Comment by ioquatix** [comment]
Okay, I think that makes sense. Do you think you can submit a PR with some specs?

**Comment by ainar-g** [comment]
Yes. In a few days.

**Comment by ioquatix** [comment]
If you have time to revisit this that would be great. There are some biggish changes in 0.15.0 relating to managing the life cycle of containers using `Async::Container::Controller`.

**Comment by ainar-g** [comment]
Ah, sorry, the project I was working on has switched teams, and I don't work with Ruby at all any more.

Should I close the issue?

**Comment by ioquatix** [comment]
The entire design of the forked container has changed so hopefully this is no longer an issue.
