### ISSUE TITLE
Running in Hybrid mode does not work in Ruby < 2.5

### ISSUE THREAD

**Issue by davidor** [socketry/async-container#16]
Trying to run falcon in hybrid mode in Ruby 2.4 crashes with this error:
`async-container-0.16.6/lib/async/container/hybrid.rb:45: syntax error, unexpected keyword_rescue, expecting keyword_end`

The reason is that `hybrid.rb` contains a `rescue`/`ensure` inside a `do` block which is valid syntax only since Ruby 2.5. See the first item in the "New features" section https://www.ruby-lang.org/en/news/2017/12/25/ruby-2-5-0-released/

I see two possible solutions: either refactor that part of the code, or raise the minimum version of Ruby required in the gemspec.

**Comment by ioquatix** [comment]
You are correct. To be honest, Ruby 2.5 is a minimum requirement across a lot of the gems now and 2.4 is EOL for several months. So, we will set the requirement to be 2.5.
