### ISSUE TITLE
Test suite left sleeping `dots` process on each run

### ISSUE THREAD

**Issue by felixonmars** [socketry/async-container#24]
After running the test suite, a `dots` process is always left running (actually sleeping). This seems to be caused by the `restarts children when receiving SIGHUP` test, as the child PID changes after receiving SIGHUP and the `after` cleaner doesn't know this.

**Comment by ioquatix** [comment]
Okay, I see the problem, I'm going to rewrite these tests in sus too, so I'll fix it at the same time.

**Comment by ioquatix** [comment]
Okay, this should be fixed now on main.
